#! /bin/sh

killall -9 sxhkd dunst picom nm-applet blueman-applet flameshot polybar mopidy mullvad-vpn

feh --bg-fill ~/Pictures/Backgrounds/Moon.jpg &
mopidy &
sxhkd &
$HOME/.config/polybar/launch.sh &
# xfce4-power-manager &
picom --config ~/.config/picom/picom.conf &
nm-applet &
blueman-applet &
flameshot &
dunst &
mullvad-vpn &
# keep same cursor theme
xsetroot -cursor_name left_ptr &
xset r rate 200 30 &

# Code, Browser, music, games, social, media, files
bspc monitor DP-4 -d 1 4 5
bspc monitor HDMI-0 -d 2 6 7
bspc monitor DP-2 -d 3 8 9

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_mod mod4
bspc config pointer_action1 move

bspc config normal_border_color     "#19191C"
bspc config focused_border_color     "#FFFFFF"

bspc rule -a Termite                            desktop='1'                 follow=on
bspc rule -a firefox                            desktop='2'                 follow=on
bspc rule -a firefoxdeveloperedition            desktop='2'                 follow=on
bspc rule -a Steam                              desktop='4'
bspc rule -a discord                            desktop='5'                 follow=on
bspc rule -a Lutris                             desktop='4'                 follow=on
bspc rule -a Thunar                             desktop='7'                 follow=on
bspc rule -a minecraft-launcher                 desktop='4'                 follow=on
bspc rule -a Zathura                            desktop='8'                 follow=on           state=tiled
