# Colors (Alabaster Dark)
# author tonsky

# [colors.primary]
# background = '#0E1415'
# foreground = '#CECECE'
#
# [colors.cursor]
# text = '#0E1415'
# cursor = '#CECECE'
#
# [colors.normal]
# black = '#0E1415'
# red = '#e25d56'
# green = '#73ca50'
# yellow = '#e9bf57'
# blue = '#4a88e4'
# magenta = '#915caf'
# cyan = '#23acdd'
# white = '#f0f0f0'
#
# [colors.bright]
# black = '#777777'
# red = '#f36868'
# green = '#88db3f'
# yellow = '#f0bf7a'
# blue = '#6f8fdb'
# magenta = '#e987e9'
# cyan = '#4ac9e2'
# white = '#FFFFFF'

[colors.primary]
background = '#0e1415'
foreground = '#cecece'

[colors.cursor]
text = '#0e1415'
cursor = '#cd974b'

[colors.selection]
text = '#000000'
background = '#293334'

[colors.normal]
black = '#000000'
red = '#d2322d'
green = '#6abf40'
yellow = '#cd974b'
blue = '#217EBC'
magenta = '#9B3596'
cyan = '#178F79'
white = '#cecece'

[colors.bright]
black = '#333333'
red = '#c33c33'
green = '#95cb82'
yellow = '#dfdf8e'
blue = '#71aed7'
magenta = '#cc8bc9'
cyan = '#47BEA9'
white = '#ffffff'
# Cursor colors
# Selection colors
# Normal colors
# Bright colors
